### ISSUE TITLE
Investigacion de organizaciones

### ISSUE THREAD

**Issue by JonathanGrimaldo** [JonathanGrimaldo/hackatonlaunchx#10]
Investigación de organizaciones

* Investigar el nombre de algunas organizaciones ( Mínimo 4 )
* Investigar santuarios  (Mínimo 4)

Ocupamos saber la ubicaciones y una breve descripción

**Comment by migueltrujillo07** [comment]
Ya avance con la invesigación 
Te dejo el link del doc
https://docs.google.com/document/d/16yYtLLk8ZvaOISWkU9Atm4-WLw6re8O80td3ybFUsoY/edit?usp=sharing

**Comment by JonathanGrimaldo** [comment]
Coool!! lo agregare al teams pa tenerlo a la mano
