### ISSUE TITLE
Documentación - diagramas

### ISSUE THREAD

**Issue by JonathanGrimaldo** [JonathanGrimaldo/hackatonlaunchx#3]
- Creación de requisitos (Paso 1)

- [x] Buyer Persona - Jonathan

- [x] Generales - Jonas

- [x]  Funcionales - Jonathan

- [x] No funcionales - Marco

- [x] User  - Marco

- Creación de diagramas (Paso 2) **Pendiente

**Comment by marcocarcamo-tech** [comment]
Hola Jonathan, hice el documento de cero para ir agregando la información y poder tenerlo centralizado, puedes agregar tu contribución de los requerimientos generales y funcionales para discutirlos después [https://docs.google.com/document/d/1N7mUxO5fKlz5_pKoFAUM2UXOkcYVkZGDKnMaQcEUQps/edit](url)

**Comment by JonathanGrimaldo** [comment]
@marcocarcamo-tech  creo que solo esta pendiente:

1.  el nombre del proyecto
2. el responsable funcional denominado por el equipo de Software.
3. En los requerimientos no funcionales, algunos puntos los deje entre asteriscos para rellenar esa información, ya que aún no la tenemos

**Comment by JonathanGrimaldo** [comment]
La parte de User ya esta? 👀

**Comment by marcocarcamo-tech** [comment]
Sí ya está, pero lo hice en una plantilla de Miró, lo agrego un poco más tarde.

**Comment by JonathanGrimaldo** [comment]
Va, va me parece bien iniciare a investigar sobre el mapa c:

**Comment by marcocarcamo-tech** [comment]
La parte de user y buyer persona en donde los juntamos?

**Comment by JonathanGrimaldo** [comment]
Yo la puse en el grupo de teams jeje

![image](https://user-images.githubusercontent.com/50802445/168453234-5e5930f3-9682-4ae6-882f-b452417fe9c3.png)

**Comment by JonathanGrimaldo** [comment]
Igual podemos hacer 1 word para cada archivo

**Comment by marcocarcamo-tech** [comment]
Sería bueno tenerlo en un documento, si quieres lo hago más tarde para tener dos pdf bien acotados.

**Comment by JonathanGrimaldo** [comment]
Si, mejor para que quede en un solo archivo 🆒
