### ISSUE TITLE
Arquitectura de base de datos

### ISSUE THREAD

**Issue by JonathanGrimaldo** [JonathanGrimaldo/hackatonlaunchx#9]
Crear base de datos 

Campos:

coordenada
nombre de la organización
descripción de evento/santuario/organización **Esta info la investigara Miguel
*Si faltan campos agregarlos si es necesario

Crear Api conection
**Pendiente

**Comment by JonathanGrimaldo** [comment]
@Andrea

**Comment by marcocarcamo-tech** [comment]
Jonathan puedes asignarlos a la derecha en donde dice assignees :D

**Comment by JonathanGrimaldo** [comment]
Esque no me aparece :c deja cierro y abro sesion

**Comment by AndreaCuriel** [comment]
Hola chicos, ya esta la estructura de la API y la creación de las tablas con prisma.  Únicamente faltaría que le den el visto bueno para ver si le agregamos o cambiamos algo, aparte de agregar la información que se necesita en cada tabla (algunas columnas e información)

repo:  https://github.com/AndreaCuriel/hackaton-launchX-API
